## Limpieza y preparación de datos de E-Commerce

Este proyecto tiene como objetivo explorar, limpiar y preparar un conjunto de datos de comercio electrónico para su posterior análisis.

Durante el proceso se revisará la calidad de los datos, incluyendo valores faltantes, registros duplicados, tipos de datos, inconsistencias en los valores de texto, formatos de fechas y otros aspectos que puedan afectar el análisis.

In [ ]:
#importamos, cargamos y mostramos datos
import pandas as pd
import numpy as np

ecommerce = pd.read_csv("D:/practicaPandas/proyectoAnalisis1/ecommerce_sales_customer_analytics_150k.csv")
costumer_master = pd.read_csv("D:/practicaPandas/proyectoAnalisis1/customer_master.csv")
order_items = pd.read_csv("D:/practicaPandas/proyectoAnalisis1/order_items.csv")
product_catalog = pd.read_csv("D:/practicaPandas/proyectoAnalisis1/product_catalog.csv")

### 1. Exploracion inicial de los datos

Analizaré los datos para entender como esta constituido el dataset, sus columnas y datos.

In [3]:
ecommerce.head()

,order_id,order_date,order_time,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,16:37:47,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,01:22:36,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,14:24:21,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,07:20:26,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,09:46:21,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

In [4]:
ecommerce.shape

(138116, 46)

In [5]:
ecommerce.columns

Index(['order_id', 'order_date', 'order_time', 'order_status', 'sales_channel',
       'customer_id', 'customer_name', 'customer_age', 'gender',
       'customer_segment', 'customer_type', 'customer_city', 'customer_state',
       'customer_country', 'region', 'customer_postal_code', 'payment_method',
       'payment_status', 'currency', 'shipping_method', 'warehouse',
       'delivery_days', 'estimated_delivery_days', 'delivery_status',
       'return_status', 'return_reason', 'customer_rating', 'review_sentiment',
       'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code',
       'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity',
       'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost',
       'net_sales', 'product_cost', 'profit', 'profit_margin_percentage',
       'customer_lifetime_value', 'is_repeat_customer',
       'customer_order_count'],
      dtype='str')

In [6]:
ecommerce.info()

<class 'pandas.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  str
 1   order_date                138116 non-null  str
 2   order_time                138116 non-null  str
 3   order_status              138116 non-null  str
 4   sales_channel             138116 non-null  str
 5   customer_id               138116 non-null  str
 6   customer_name             138116 non-null  str
 7   customer_age              138116 non-null  int64
 8   gender                    138116 non-null  str
 9   customer_segment          138116 non-null  str
 10  customer_type             138116 non-null  str
 11  customer_city             138116 non-null  str
 12  customer_state            138116 non-null  str
 13  customer_country          138116 non-null  str
 14  region                    138116 non-null  str
 15  customer_postal_code      138116 non-null  int64
 16  payment_method            138116 non-null  str
 17  payment_status            138116 non-null  str
 18  currency                  138116 non-null  str
 19  shipping_method           138116 non-null  str
 20  warehouse                 138116 non-null  str
 21  delivery_days             113559 non-null  float64
 22  estimated_delivery_days   113559 non-null  float64
 23  delivery_status           138116 non-null  str
 24  return_status             9462 non-null    str
 25  return_reason             9462 non-null    str
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  str
 28  customer_review           113559 non-null  str
 29  marketing_channel         138116 non-null  str
 30  campaign_name             54883 non-null   str
 31  coupon_code               27614 non-null   str
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), float64(12), int64(6), str(27)
memory usage: 75.3 MB

In [7]:
ecommerce.duplicated().sum()

np.int64(0)

## 2. Missing values análisis

Antes de limpiar el dataset, analizaré los valores faltantes en cada columna
para determinar si los valores faltante corresponde a un error o ausencia valida de información.

In [8]:
datos_faltantes = ecommerce.isna().sum()

porcentaje_datos_faltantes = (
    datos_faltantes / len(ecommerce)
    )*100

tabla_faltantes = pd.DataFrame({
    "valores faltantes" : datos_faltantes,
    "porcentaje faltantes" : porcentaje_datos_faltantes
})

tabla_faltantes = tabla_faltantes[
    tabla_faltantes["valores faltantes"] > 0
    ].sort_values(
        by="porcentaje faltantes",
        ascending=False
    )    
tabla_faltantes

                         valores faltantes  porcentaje faltantes
return_status                       128654             93.149237
return_reason                       128654             93.149237
coupon_code                         110502             80.006661
campaign_name                        83233             60.263112
delivery_days                        24557             17.779982
customer_rating                      24557             17.779982
estimated_delivery_days              24557             17.779982
customer_review                      24557             17.779982
review_sentiment                     24557             17.779982

### Entediendo datos faltantes

Analizaré los datos faltantes obtenidos para determinar si constituyen un problema real
de calidad de datos o simplemente son casos donde la informacion no aplica.

In [9]:
ecommerce["return_status"].value_counts(dropna=False)

return_status
NaN         128654
Returned      9462
Name: count, dtype: int64

In [10]:
ecommerce["return_reason"].value_counts(dropna=False)

return_reason
NaN                        128654
Wrong Product                1237
Other                        1208
Changed Mind                 1204
Size Issue                   1182
Defective Product            1174
Late Delivery                1172
Product Not as Expected      1147
Damaged Product              1138
Name: count, dtype: int64

In [11]:
ecommerce[["return_status","return_reason"]].value_counts(dropna=False)

return_status  return_reason
NaN            NaN                        128654
Returned       Wrong Product                1237
               Other                        1208
               Changed Mind                 1204
               Size Issue                   1182
               Defective Product            1174
               Late Delivery                1172
               Product Not as Expected      1147
               Damaged Product              1138
Name: count, dtype: int64

In [12]:
ecommerce["return_status"] = ecommerce["return_status"].fillna("No reembolsado")
ecommerce["return_reason"] = ecommerce["return_reason"].fillna("No aplica")

ecommerce[["return_status","return_reason"]].value_counts(dropna=False)

return_status   return_reason
No reembolsado  No aplica                  128654
Returned        Wrong Product                1237
                Other                        1208
                Changed Mind                 1204
                Size Issue                   1182
                Defective Product            1174
                Late Delivery                1172
                Product Not as Expected      1147
                Damaged Product              1138
Name: count, dtype: int64

Al analizar `return_status` y `return_reason`, se observa que los valores faltantes corresponden a registros que no presentan información de devolución. Por esta razón, se reemplazarán los valores faltantes de `return_status` por `"No reembolsado"` y los de `return_reason` por `"No aplica"`. Esto permitirá representar explícitamente la ausencia de información de devolución y facilitar su interpretación en análisis posteriores.

In [13]:
ecommerce["coupon_code"].value_counts(dropna=False).head(15)

coupon_code
NaN       110502
SAVE39       731
SAVE49       727
SAVE40       719
SAVE12       716
SAVE33       715
SAVE26       712
SAVE25       711
SAVE15       709
SAVE36       709
SAVE46       707
SAVE44       704
SAVE21       704
SAVE27       702
SAVE22       702
Name: count, dtype: int64

In [14]:
analisis_cupon = ecommerce.groupby(
    ecommerce["coupon_code"].isna().map({
        True : "Sin cupon",
        False : "Con cupon"
    })
)["discount_amount"].agg(["count","mean","min","max"])

analisis_cupon["porcentaje"] = (
    analisis_cupon["count"]/analisis_cupon["count"].sum()
)*100

analisis_cupon

              count        mean  min      max  porcentaje
coupon_code
Con cupon     27614  235.821261  0.0  5046.32   19.993339
Sin cupon    110502  238.071515  0.0  6759.02   80.006661

In [15]:
ecommerce["coupon_code"] = ecommerce["coupon_code"].fillna("No cupon")

ecommerce["coupon_code"].value_counts(dropna=False).head(15)

coupon_code
No cupon    110502
SAVE39         731
SAVE49         727
SAVE40         719
SAVE12         716
SAVE33         715
SAVE26         712
SAVE25         711
SAVE15         709
SAVE36         709
SAVE46         707
SAVE44         704
SAVE21         704
SAVE27         702
SAVE22         702
Name: count, dtype: int64

### Análisis de `coupon_code`

Se identificaron valores faltantes en `coupon_code`. Para determinar si estos registros requerían un tratamiento específico, se comparó `discount_amount` entre los registros con y sin código de cupón.

Los resultados mostraron que aproximadamente el 20% de los registros cuentan con un código de cupón, mientras que el 80% no presenta uno. Además, el valor promedio de `discount_amount` fue similar entre ambos grupos, por lo que no se identificó un comportamiento que justificara un tratamiento diferente para los registros sin código.

Por este motivo, los valores faltantes de `coupon_code` se interpretaron como registros sin cupón y fueron reemplazados por `"No cupon"`. Finalmente, se verificó la distribución de la variable después de la transformación.

In [16]:
ecommerce["campaign_name"].value_counts(dropna=False)

campaign_name
NaN                   83233
Default_Campaign      22989
Google_Search_Q1       2748
Google_Shopping        2746
Google_Display         2731
FB_Retargeting         2270
FB_Dynamic             2233
Friend_Invite          2232
Referral_Program       2198
FB_Prospecting         2161
Insta_Influencer       1822
Insta_Reels            1799
Insta_Stories          1773
Abandoned_Cart         1520
Weekly_Newsletter      1459
Promo_Email            1459
Influencer_Program     1404
Affiliate_Partner      1339
Name: count, dtype: int64

In [17]:
ecommerce.groupby(ecommerce["campaign_name"].isna().map({
    True : "Sin campaña",
    False : "Con campaña"
    }))["marketing_channel"].value_counts()

campaign_name  marketing_channel
Con campaña    Organic Search       11009
               Google Ads            8225
               Direct                8182
               Facebook Ads          6664
               Instagram             5394
               Email Marketing       4438
               Referral              4430
               Affiliate             2743
               TikTok                2201
               YouTube               1597
Sin campaña    Organic Search       16733
               Google Ads           12408
               Direct               12333
               Facebook Ads          9987
               Instagram             8407
               Email Marketing       6780
               Referral              6761
               Affiliate             4105
               TikTok                3236
               YouTube               2483
Name: count, dtype: int64

In [18]:
ecommerce.groupby(
    ecommerce["campaign_name"].isna().map({
        True: "Sin campaña",
        False: "Con campaña"
    })
)["discount_amount"].agg(["count", "mean", "min", "max"])

               count        mean  min      max
campaign_name
Con campaña    54883  237.539780  0.0  5336.38
Sin campaña    83233  237.675574  0.0  6759.02

In [19]:
ecommerce.groupby(
    ecommerce["campaign_name"].isna().map({
        True: "Sin campaña",
        False: "Con campaña"
    })
)["coupon_code"].value_counts()

campaign_name  coupon_code
Con campaña    No cupon       43755
               SAVE36           306
               SAVE25           303
               SAVE37           298
               SAVE18           296
                              ...
Sin campaña    SAVE10           384
               SAVE37           383
               SAVE35           382
               SAVE29           369
               SAVE24           364
Name: count, Length: 82, dtype: int64

In [20]:
ecommerce["campaign_name"] = ecommerce["campaign_name"].fillna("Campaña desconocida")

ecommerce["campaign_name"].value_counts(dropna=False)

campaign_name
Campaña desconocida    83233
Default_Campaign       22989
Google_Search_Q1        2748
Google_Shopping         2746
Google_Display          2731
FB_Retargeting          2270
FB_Dynamic              2233
Friend_Invite           2232
Referral_Program        2198
FB_Prospecting          2161
Insta_Influencer        1822
Insta_Reels             1799
Insta_Stories           1773
Abandoned_Cart          1520
Weekly_Newsletter       1459
Promo_Email             1459
Influencer_Program      1404
Affiliate_Partner       1339
Name: count, dtype: int64

Se analizaron los valores faltantes de `campaign_name` comparándolos con `marketing_channel` y `coupon_code`. Los registros sin nombre de campaña aparecen asociados a diferentes canales de marketing y, además, algunos de estos registros presentan códigos de cupón. Esto indica que la ausencia de `campaign_name` no necesariamente representa la ausencia de una campaña, por lo que no existe evidencia suficiente para reemplazar los valores faltantes por `"Sin campaña"`. En consecuencia, se utilizó `"Campaña desconocida"` para representar explícitamente que no se dispone del nombre de la campaña.

In [21]:
ecommerce["delivery_days"].isna().sum()

np.int64(24557)

In [22]:
ecommerce.loc[ecommerce["delivery_days"].isna(),["order_status","delivery_status"]].value_counts(dropna=False)

order_status  delivery_status
Returned      Cancelled          9462
Cancelled     Cancelled          8398
Pending       Cancelled          6697
Name: count, dtype: int64

Análisis datos faltantes`delivery_days`

In [23]:
ecommerce["customer_rating"].isna().sum()

np.int64(24557)

In [24]:
ecommerce.loc[ecommerce["customer_rating"].isna(),["order_status","delivery_status"]].value_counts(dropna=False)

order_status  delivery_status
Returned      Cancelled          9462
Cancelled     Cancelled          8398
Pending       Cancelled          6697
Name: count, dtype: int64

Análisis datos faltantes`customer_rating`

In [25]:
ecommerce["estimated_delivery_days"].isna().sum()

np.int64(24557)

In [26]:
ecommerce.loc[ecommerce["estimated_delivery_days"].isna(),["order_status","delivery_status"]].value_counts(dropna=False)

order_status  delivery_status
Returned      Cancelled          9462
Cancelled     Cancelled          8398
Pending       Cancelled          6697
Name: count, dtype: int64

Análisis datos faltantes`estimated_delivery_days`

In [27]:
ecommerce["customer_review"].isna().sum()

np.int64(24557)

In [28]:
ecommerce.loc[ecommerce["customer_review"].isna(),["order_status","delivery_status"]].value_counts(dropna=False)

order_status  delivery_status
Returned      Cancelled          9462
Cancelled     Cancelled          8398
Pending       Cancelled          6697
Name: count, dtype: int64

Análisis datos faltantes`customer_review`

In [29]:
ecommerce["review_sentiment"].isna().sum()

np.int64(24557)

In [30]:
ecommerce.loc[ecommerce["review_sentiment"].isna(),["order_status","delivery_status"]].value_counts(dropna=False)

order_status  delivery_status
Returned      Cancelled          9462
Cancelled     Cancelled          8398
Pending       Cancelled          6697
Name: count, dtype: int64

Analisis datos faltantes`review_sentiment`

Se identificaron valores faltantes en `delivery_days`, `customer_rating`, `estimated_delivery_days`, `customer_review` y `review_sentiment`, todos correspondientes a los mismos 24.557 registros (17,78 % del dataset). Al analizar estos registros, se comprobó que corresponden a pedidos cuyo `delivery_status` es `"Cancelled"`. Por este motivo, los valores faltantes representan información que no resulta aplicable para estos pedidos, por lo que se conservaron como `NaN` en lugar de asignar valores artificiales.

### Resumen del análisis y tratamiento de valores faltantes

Se analizaron los valores faltantes de forma individual, considerando el contexto y la relación entre las variables antes de aplicar cualquier transformación. Los faltantes de `return_status`, `return_reason`, `coupon_code` y `campaign_name` fueron tratados según su significado, mientras que los de `delivery_days`, `customer_rating`, `estimated_delivery_days`, `customer_review` y `review_sentiment` se conservaron como `NaN` al corresponder a pedidos con `delivery_status = "Cancelled"`.

El objetivo fue tratar únicamente los faltantes que podían interpretarse de forma justificada, conservando aquellos que representan una ausencia válida de información.

## 3. Análisis y validación de calidad de los datos

In [31]:
ecommerce.dtypes

order_id                        str
order_date                      str
order_time                      str
order_status                    str
sales_channel                   str
customer_id                     str
customer_name                   str
customer_age                  int64
gender                          str
customer_segment                str
customer_type                   str
customer_city                   str
customer_state                  str
customer_country                str
region                          str
customer_postal_code          int64
payment_method                  str
payment_status                  str
currency                        str
shipping_method                 str
warehouse                       str
delivery_days               float64
estimated_delivery_days     float64
delivery_status                 str
return_status                   str
return_reason                   str
customer_rating             float64
review_sentiment                str
customer_review                 str
marketing_channel               str
campaign_name                   str
coupon_code                     str
loyalty_points_earned         int64
loyalty_points_redeemed       int64
quantity                      int64
gross_sales                 float64
discount_amount             float64
tax_amount                  float64
shipping_cost               float64
net_sales                   float64
product_cost                float64
profit                      float64
profit_margin_percentage    float64
customer_lifetime_value     float64
is_repeat_customer             bool
customer_order_count          int64
dtype: object

In [32]:
ecommerce[["order_date","order_time"]].head()

   order_date order_time
0  2023-11-06   16:37:47
1  2025-12-24   01:22:36
2  2021-07-05   14:24:21
3  2023-01-21   07:20:26
4  2022-05-13   09:46:21

In [33]:
ecommerce["order_date"] = pd.to_datetime(
    ecommerce["order_date"],
    format="%Y-%m-%d"
    )

ecommerce["order_date"].head()

0   2023-11-06
1   2025-12-24
2   2021-07-05
3   2023-01-21
4   2022-05-13
Name: order_date, dtype: datetime64[us]

In [34]:
ecommerce['order_time'] = pd.to_datetime(
    ecommerce['order_time'],
    format='%H:%M:%S'
).dt.time

ecommerce["order_time"].head()

0    16:37:47
1    01:22:36
2    14:24:21
3    07:20:26
4    09:46:21
Name: order_time, dtype: object

Se observó que las columnas `order_date` y `order_time` se encontraban almacenadas como cadenas de texto (`str`). Se transformaron a tipos de fecha y hora, respectivamente, con el objetivo de facilitar su manipulación y permitir realizar análisis temporales posteriormente, en caso de ser necesario.

In [36]:
ecommerce.select_dtypes(include="str").nunique().sort_values()

return_status             2
customer_type             3
review_sentiment          3
gender                    3
customer_segment          4
shipping_method           4
order_status              4
sales_channel             4
payment_status            4
delivery_status           4
region                    5
payment_method            7
customer_country          7
currency                  7
return_reason             9
marketing_channel        10
campaign_name            18
warehouse                19
customer_review          25
customer_state           38
coupon_code              41
customer_city         15516
customer_name         21564
customer_id           24911
order_id             138116
dtype: int64

In [53]:
columnas_categoricas = [
    "return_status",
    "customer_type",
    "review_sentiment",
    "gender",
    "customer_segment",
    "shipping_method",
    "order_status",
    "sales_channel",
    "payment_status",
    "delivery_status",
    "region",
    "payment_method"
]

ecommerce[columnas_categoricas].head(10)

,return_status,customer_type,review_sentiment,gender,customer_segment,shipping_method,order_status,sales_channel,payment_status,delivery_status,region,payment_method
0,No reembolsado,Loyal,Positive,Male,Consumer,Standard,Completed,Mobile App,Paid,On Time,South,Digital Wallet
1,No reembolsado,Loyal,Positive,Male,Premium,Economy,Completed,Website,Pending,On Time,South,Debit Card
2,No reembolsado,Loyal,Positive,Female,Premium,Express,Completed,Mobile App,Paid,On Time,East,Cash on Delivery
3,No reembolsado,Loyal,Positive,Male,Consumer,Express,Completed,Social Media,Paid,On Time,South,Debit Card
4,No reembolsado,Loyal,Neutral,Female,Consumer,Standard,Completed,Social Media,Paid,Delayed,West,Digital Wallet
5,No reembolsado,Returning,NaN,Female,Consumer,Standard,Pending,Website,Paid,Cancelled,Central,Credit Card
6,No reembolsado,Loyal,Neutral,Female,Consumer,Economy,Completed,Mobile App,Paid,Delayed,South,Credit Card
7,No reembolsado,Loyal,Positive,Female,VIP,Standard,Completed,Mobile App,Paid,On Time,East,PayPal
8,No reembolsado,Loyal,Neutral,Female,Consumer,Same Day,Completed,Mobile App,Paid,On Time,East,Credit Card
9,No reembolsado,Loyal,Positive,Female,Consumer,Standard,Completed,Mobile App,Paid,On Time,East,Credit Card

In [55]:
ecommerce[columnas_categoricas] = ecommerce[columnas_categoricas].astype("category")

ecommerce[columnas_categoricas].dtypes

return_status       category
customer_type       category
review_sentiment    category
gender              category
customer_segment    category
shipping_method     category
order_status        category
sales_channel       category
payment_status      category
delivery_status     category
region              category
payment_method      category
dtype: object

Se transformaron las variables categóricas al tipo `category` para facilitar su gestión y optimizar su representación dentro del DataFrame.

## Definición de preguntas de negocio

### Definición de preguntas de negocio

### 1. Marketing, campañas y cupones

- ¿Las campañas están asociadas con mayores ventas?
- ¿Cómo se relaciona el uso de cupones con el volumen de pedidos?
- ¿Qué campaña tiene mayor `profit`?
- ¿Qué `marketing_channel` concentra más ventas?

### 2. Comportamiento de los clientes

- ¿Qué tipo de clientes realiza más pedidos?
- ¿Qué tipo de clientes genera mayor gasto?
- ¿Qué tipo de clientes genera mayor `profit`?

### 3. Distribución geográfica

- ¿En qué ciudades se concentra el mayor volumen de ventas?
- ¿Qué ciudades generan mayor `profit`?
- ¿Las ciudades con mayor volumen de ventas son también las más rentables?

### 4. Evolución temporal

- ¿Cómo han evolucionado las ventas a lo largo del tiempo?
- ¿Qué año presenta el mayor volumen de ventas?
- ¿Qué meses concentran el mayor volumen de ventas?
- ¿Qué días de la semana concentran más pedidos?
- ¿En qué horas se concentra el mayor número de pedidos?

### 5. Envíos, devoluciones y satisfacción

- ¿Existe alguna relación entre el método de envío y las devoluciones?
- ¿Existen diferencias en la satisfacción de los clientes según el método de envío?
- ¿Qué métodos de envío presentan mayor cantidad de devoluciones?
- ¿Qué métodos de envío presentan menores niveles de satisfacción?

## Transformación de datos

In [67]:
ecommerce["order_year"] = ecommerce["order_date"].dt.year

ecommerce["order_month"] = ecommerce["order_date"].dt.month

ecommerce["order_weekday"] = ecommerce["order_date"].dt.day_name()

ecommerce["order_hour"] = ecommerce["order_time"].apply(lambda x: x.hour)

Se crearon nuevas columnas (`order_hour`, `order_month`, `order_weekday` y `order_year`) para facilitar el análisis y dar respuesta a las preguntas de negocio relacionadas con la evolución temporal de las ventas y los pedidos.